### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by dee-y** [romankh3/movietracking#7]
Hi @romankh3, i will start with this one. Will provide the logo for this project after am done so you can give me your opinions. 

Dee-y.

**Comment by romankh3** [comment]
Hi @dee-y, Can't wait to see your results!

Roman.

**Comment by dee-y** [comment]
Alright i came up with this concept, the letter "M" and "T" fused into a movie camera. The logo is also excellent for favicon style. So what do you think? if you like the idea, any input on color choice?
![movietracking-01](https://user-images.githubusercontent.com/36637989/42052689-65a98a86-7b07-11e8-88af-05b373c41af1.png)

**Comment by romankh3** [comment]
Hi, @dee-y.
creating movie camera using M and T letters - great idea! Great work!
I like results with text after movie camera. it creates an impression that camera shows this text.

Favicon I like, too.

About colors, I prefer second case: orange and blue.

**Comment by dee-y** [comment]
Hello @romankh3 i made a few extras to add life to the logo. 
![logotype whitebg](https://user-images.githubusercontent.com/36637989/42087979-cee392c0-7b8f-11e8-89a4-1688e7472024.png)

 are you ok with this? so i go ahead and make a pull request

**Comment by romankh3** [comment]
@dee-y, What do you think about the line under the movie camera and text? 
I think we can see how it looks like.

**Comment by dee-y** [comment]
Hi @romankh3 what do you think of these?
![logotype check-01-01](https://user-images.githubusercontent.com/36637989/42104897-52aa126a-7bc6-11e8-9747-ca078ea9bd49.png)

**Comment by romankh3** [comment]
I see it and understand that previous version without line I like more! What do you think?

**Comment by dee-y** [comment]
Yes you are right, without line is good.

**Comment by romankh3** [comment]
I think you can make pull-request! 

FYI: Today I'm going on vacation and don't know about quality of the intetnet connection on their place. Next time I'll answer in a week!

**Comment by dee-y** [comment]
wow...lolz gonna miss you for a week...making the pull request now. Safe trip!

**Comment by romankh3** [comment]
@dee-y ,great work. Merged.
